package com.thecodeinnovator.sudokuserver.puzzleenum;

public enum SudokuElementSizeN {
    ELEMENT_0,
    ELEMENT_1,
    ELEMENT_2,
    ELEMENT_3,
    ELEMENT_4,
    ELEMENT_5,
    ELEMENT_6,
    ELEMENT_7,
    ELEMENT_8,
    ELEMENT_9,
    ELEMENT_10,
    ELEMENT_11,
    ELEMENT_12,
    ELEMENT_13,
    ELEMENT_14,
    ELEMENT_15,
    ELEMENT_16,
    ELEMENT_17,
    ELEMENT_18,
    ELEMENT_19,
    ELEMENT_20,
    ELEMENT_21,
    ELEMENT_22,
    ELEMENT_23,
    ELEMENT_24,
    ELEMENT_25
}
